import type { Metadata } from 'next'
import './globals.css'
import 'material-symbols'

// NOTE - Fonts imports

export const metadata: Metadata = {
  title: 'Vigel | Sua ideia tornando realidade',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="scrool-smooth focus:scroll-auto">
      <head>
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Rokkitt:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
